title: Security Differently
email: john@security-differently.com
phone: 16128025368
phone-formatted: (612) 802-5368
social-linkedin: https://www.linkedin.com/in/jbenninghoff/

current-year: 2024
copyright: Security Differently.  All Rights Reserved.

meta-description:
meta-keywords: 

# Exclude ruby framework
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - bootstrap.sh
  - clean.sh
  - tmp
  - vendor
